[theme]
primaryColor="#4A90E2"
backgroundColor="#F0F2F6"
secondaryBackgroundColor="#FFFFFF"
textColor="#333333"
font="sans serif"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false